version: '3.1'
services:
 postgres:
   image: postgres:11.2-alpine
   volumes:
     - ".docker/postgres:/var/lib/postgresql/data:delegated"
   ports:
     - "127.0.0.1:5432:5432"
   environment:
     POSTGRES_USER: 'student'
     POSTGRES_PASSWORD: 'student'
     POSTGRES_DB: 'studentdb'
